disabled_rules:
  - file_length
  - function_body_length
  - multiple_closures_with_trailing_closure
  - nesting
  - todo
  - trailing_whitespace
  - type_body_length
  - xctfail_message

opt_in_rules:
  - file_header
  - modifier_order
  - sorted_imports

trailing_comma:
    mandatory_comma: true

line_length: 180

excluded:
  - .build/**
