name: push
on: push

jobs:
  lint:
    runs-on: macos-13
    timeout-minutes: 10
    name: Lint
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}
      - name: SwiftPM Cache
        uses: actions/cache@v3
        with:
          path: .build
          key: ${{ runner.os }}-spm-plugin-${{ hashFiles('**/Package.resolved') }}
      - name: Lint Fix
        run: |
          swift package plugin --allow-writing-to-package-directory lint-fix
      - name: Lint Check
        run: |
          swift package plugin lint-check
      - name: Push
        run: |
          git remote set-url origin https://github-actions:${{ secrets.CI_TOKEN }}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "github-actions"
          git config --global user.email "22269397+maiyama18@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "Apply lint"; \
            git push
          fi

  test:
    needs: lint
    timeout-minutes: 30
    runs-on: macos-13
    name: Test
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3'
      - uses: actions/checkout@v3
      - uses: mikehardy/buildcache-action@v2
      - name: SwiftPM Cache
        uses: actions/cache@v3
        with:
          path: /tmp/SourcePackages
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
      - name: Test
        run: |
          xcodebuild -scheme iOSAppDev -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone 14,OS=16.4" -clonedSourcePackagesDirPath /tmp/SourcePackages -resultBundlePath TestResults -skipPackagePluginValidation test
      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: always()
